services:
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile.mcp
    ports:
      - "8000:8000"
    volumes:
      - ./data:/tmp/chroma
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}

  gradio-app:
    build:
      context: .
      dockerfile: Dockerfile.gradio
    ports:
      - "7860:7860"
    depends_on:
      - mcp-server
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}