services:
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile.mcp
    ports:
      - "8000:8000"
    volumes:
      - ./data:/tmp/chroma
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}

  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    depends_on:
      - mcp-server
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}